### ISSUE TITLE
Validity Check Fails

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-rospy#3]
When trying to install `ros-melodic-desktop-full`, this package fails it's validity check. If this could be fixed, it would be much appreciated.

**Comment by mse0** [comment]
It seems to be downloading the wrong file for some reason. I was able to download the tar.gz file listed in the PKGBUILD manually in my web browser. It downloaded as ros_comm-release-release-melodic-rospy.tar.gz but the sha256 matched. I renamed it ros-melodic-rospy-1.14.3-0.tar.gz and ran makepkg -si and it installed. Now I'm apparently having the same problem with ros-melodic-tf2-geometry-msgs 0.6.5-1. Hope that helps.

**Comment by acxz** [comment]
hmm I see, is it possible for this fix/renaming to be done through the PKGBUILD?

I guess that is what #1 and #2 are attempting to do?

**Comment by mse0** [comment]
I assume so, but I have no idea why the arch build would be downloading a different file than when I type the same thing in my web browser. Hopefully the maintainer can help us out. Btw I was able to install the entire Ros full but it took lots of little fixes. For example, you have to remove "signals" from a bunch of cmakelists that use boost because signals has been removed from the latest version of boost.

**Comment by acxz** [comment]
Ahh I see, also I just it seems like @bionade24 has just updated this repo and that fix works installed the package for me.

As such I'll go ahead and close the issue.

**Comment by bionade24** [comment]
> I assume so, but I have no idea why the arch build would be downloading a different file than when I type the same thing in my web browser. Hopefully the maintainer can help us out. Btw I was able to install the entire Ros full but it took lots of little fixes. For example, you have to remove "signals" from a bunch of cmakelists that use boost because signals has been removed from the latest version of boost.

Only `ros-melodic-ros-base` is currently "working", the other things are full of shit and may break some things. I wouldn't use them anymore, use containers or Ubuntu/Debian directly until everything is repacked. It would also be nice if you do PRs to get `ros-melodic-desktop(-full)` to the official release sources, infos are in our organization's project.
